import yaml from "js-yaml";

export async function getAlertData(): Promise<JsonExpected> {

    const response = await fetch(
        "https://raw.githubusercontent.com/samber/awesome-prometheus-alerts/refs/heads/master/_data/rules.yml",
        {},
    );
    
    if (!response.ok) {
        throw Error("All is not daijobu.");
    }
    
    const rawYml = await (await response.blob()).text();
    
    const json = yaml.load(rawYml) as JsonExpected;
    if (!json) {
        throw Error("JSON generated by js-yaml was null.");
    }
    return json;
}

type Rule = {
	name: string;
	description: string;
	query: string;
	severity: string;
	for: string;
	comments: string;
	summary: string;
};
type Exporter = {
	slug: string;
	rules?: Rule[];
	name: string;
	doc_url: string;
};
type Service = {
	name: string;
	exporters: Exporter[];
};
type Group = {
	name: string;
	services: Service[];
};
type JsonExpected = {
	groups: Group[];
};